theme: minima
title: My Blog
author: Jebin J
email: jebin.jebamony@comorin.co
description: This is my first Blog. Really interested to see the output.

# social links
github_username:  jebinj22

show_excerpts: true # set to false to remove excerpts on the homepage
